global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FixMo application
  - job_name: 'fixmo-app'
    static_configs:
      - targets: ['fixmo-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  # Nginx (if nginx-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node.js application metrics
  - job_name: 'nodejs'
    static_configs:
      - targets: ['fixmo-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['fixmo-app:3000']
    metrics_path: '/api/health'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Custom metrics endpoints
  - job_name: 'fixmo-custom-metrics'
    static_configs:
      - targets: ['fixmo-app:3000']
    metrics_path: '/api/metrics/custom'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Database metrics (if using database exporter)
  - job_name: 'database'
    static_configs:
      - targets: ['db-exporter:9113']
    scrape_interval: 30s

  # System metrics (if using node-exporter)
  - job_name: 'system'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules
rule_files:
  - "recording_rules.yml" 